version: '2'
services:
  doremi:
    build: .
    volumes:
      # TODO configurable
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - consul
    environment:
      CONSUL_URL: http://consul:8500
  consul:
    image: consul
    ports:
      - 8500:8500
